services:
  backend_app:
    build:
      context: backend/
      dockerfile: Dockerfile
    container_name: backend_app
    command: ["./start.sh"]
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./backend/:/code
    networks:
      - app_network
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend_app
    networks:
      - app_network

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    command: ["postgres", "-c", "hba_file=/var/lib/postgresql/pg_hba.conf"]
    restart: always
    env_file:
      - .env
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_hba.conf:/var/lib/postgresql/pg_hba.conf
    networks:
      - app_network

volumes:
  postgres_data:
  ..:

networks:
  app_network:
    driver: bridge