"""empty message

Revision ID: 19c044807e81
Revises: 1ca190c726e1
Create Date: 2024-09-27 00:45:19.928748

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "19c044807e81"
down_revision: Union[str, None] = "1ca190c726e1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f("uq_user_name"), "user", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_user_name"), "user", type_="unique")
    # ### end Alembic commands ###
